# Generated by Django 5.1.6 on 2025-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
